version: '3'

name: cowtrol

services:
  postgresql:
    image: postgres:alpine
    restart: unless-stopped
    ports:
      - '5431:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: pass123

  api:
    image: api
    ports:
      - '3000:3000'
    env_file:
      - ./.env
    environment:
      PORT: 3000
      DATABASE_URL: 'postgres://postgres:pass123@postgresql:5432/postgres?schema=public'
    depends_on:
      - postgresql

volumes:
  postgres_data:

networks:
  default:
    external:
      name: cowtrol
